### ISSUE TITLE
Presentation materials links broken

### ISSUE THREAD

**Issue by tolomaps** [carsonfarmer/python_geospatial#4]
The links in the [readme](https://github.com/carsonfarmer/python_geospatial/) aren't working.

**Comment by carsonfarmer** [comment]
Hi @tolomaps I can't seem to reproduce this issue? Are you referring to these links (for example):

https://dl.dropboxusercontent.com/u/14940391/python_geospatial/Presentation1.slides.html

**Comment by tolomaps** [comment]
Yes I was... though it must've been something weird this morning. Now they are working for me. Thanks!

**Comment by carsonfarmer** [comment]
Ah good... who knows how this whole "internet" thing works :stuck_out_tongue_winking_eye:
